#!/usr/bin/env bash
# Start/stop N radio-less meshtasticd (Portduino) instances that mesh over UDP multicast.
#
#   ./run_meshtasticd.sh up [N]          start N instances (default 2)
#   ./run_meshtasticd.sh down [--wipe]   stop + remove containers (--wipe also deletes state/)
#   ./run_meshtasticd.sh status          list instances, node ids, API ports
#   ./run_meshtasticd.sh logs I [args]   docker logs of instance I (e.g. logs 1 -f)
#   ./run_meshtasticd.sh tools ARGS...   run `python ARGS` in the tools image on the mesh network
#                                        with this directory mounted at /interop
#   ./run_meshtasticd.sh build-tools     build the tools image (python + meshtastic)
#
# Env:
#   MESHTASTICD_IMAGE  (default meshtastic/meshtasticd:2.7.26.54e0d8d-debian)
#   NET_MODE           bridge (default) | host
#   NET_NAME           docker network for bridge mode (default repeatertastic-mesh)
#   API_BASE_PORT      TCP API port of instance 1 (default 4410; instance I = base+I-1)
#   STATE_DIR          per-instance config + VFS (default ./state)
#   UDP                1 (default) joins the UDP multicast mesh; 0 leaves the sim radio as the only
#                      path, for the client API live tests (internal/mtclient)
#
# Instance I: container repeatertastic-mtd-I, hwid 02:00:1E:E7:A0:II -> node !1ee7a0II on 2.7.x
# (2.8+ renumbers to crc32(public_key) once its key pair exists),
# config.yaml with `Lora: Module: sim` (SimRadio without --sim, so PKI stays enabled)
# and `Config: EnableUDP: true`.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
IMAGE="${MESHTASTICD_IMAGE:-meshtastic/meshtasticd:2.7.26.54e0d8d-debian}"
NET_MODE="${NET_MODE:-bridge}"
NET_NAME="${NET_NAME:-repeatertastic-mesh}"
UDP="${UDP:-1}"
API_BASE_PORT="${API_BASE_PORT:-4410}"
STATE_DIR="${STATE_DIR:-$HERE/state}"
TOOLS_IMAGE="${TOOLS_IMAGE:-repeatertastic-interop-tools:1}"
PREFIX=repeatertastic-mtd

die() { echo "error: $*" >&2; exit 1; }

instances() { docker ps -a --filter "name=^${PREFIX}-[0-9]+$" --format '{{.Names}}' | sort -V; }

net_args() {
  if [[ "$NET_MODE" == host ]]; then
    echo "--network host"
  else
    echo "--network $NET_NAME -p 127.0.0.1:$1:$1"
  fi
}

cmd_up() {
  local n="${1:-2}"
  [[ "$n" =~ ^[0-9]+$ && "$n" -ge 1 && "$n" -le 250 ]] || die "N must be 1..250"
  if [[ "$NET_MODE" == bridge ]] && ! docker network inspect "$NET_NAME" >/dev/null 2>&1; then
    docker network create "$NET_NAME" >/dev/null
    echo "created docker network $NET_NAME"
  fi
  for ((i = 1; i <= n; i++)); do
    local name="$PREFIX-$i" port=$((API_BASE_PORT + i - 1)) hex dir
    hex=$(printf '%02X' "$i")
    dir="$STATE_DIR/node$i"
    if docker ps -a --format '{{.Names}}' | grep -qx "$name"; then
      docker start "$name" >/dev/null
      echo "$name already exists (started)"
      continue
    fi
    mkdir -p "$dir/vfs"
    cat >"$dir/config.yaml" <<EOF
# generated by run_meshtasticd.sh
Lora:
  Module: sim        # SimRadio. Do NOT use --sim: that flag also disables PKI in Router::perhapsEncode
Logging:
  LogLevel: debug
$(if [[ "$UDP" == 1 ]]; then printf 'Config:\n  EnableUDP: true    # forces network.enabled_protocols = UDP_BROADCAST at boot\n'; fi)
General:
  MaxNodes: 200
EOF
    # shellcheck disable=SC2046
    docker run -d --name "$name" \
      --user "$(id -u):$(id -g)" \
      --restart unless-stopped \
      $(net_args "$port") \
      -v "$dir:/data" \
      --label repeatertastic.interop=1 \
      "$IMAGE" \
      /usr/bin/meshtasticd -c /data/config.yaml -d /data/vfs -h "02001EE7A0$hex" -p "$port" >/dev/null
    echo "$name  hwid-node=!1ee7a0${hex,,}  api=127.0.0.1:$port  image=$IMAGE  net=$NET_MODE"
  done
  echo "waiting for TCP APIs..."
  for ((i = 1; i <= n; i++)); do
    local port=$((API_BASE_PORT + i - 1))
    for _ in $(seq 60); do
      (exec 3<>/dev/tcp/127.0.0.1/"$port") 2>/dev/null && break
      sleep 0.5
    done
  done
  echo "up. next: .venv/bin/python setup_nodes.py $(for ((i = 1; i <= n; i++)); do printf '127.0.0.1:%d ' $((API_BASE_PORT + i - 1)); done)"
}

cmd_down() {
  local names
  names=$(instances)
  [[ -n "$names" ]] && docker rm -f $names >/dev/null && echo "removed: $(echo $names)"
  if [[ "${1:-}" == --wipe ]]; then
    rm -rf "$STATE_DIR"
    echo "wiped $STATE_DIR"
  fi
  if docker network inspect "$NET_NAME" >/dev/null 2>&1; then
    docker network rm "$NET_NAME" >/dev/null 2>&1 && echo "removed network $NET_NAME" || true
  fi
}

cmd_status() {
  docker ps -a --filter "name=^${PREFIX}-" --format 'table {{.Names}}\t{{.Status}}\t{{.Image}}\t{{.Command}}'
}

cmd_logs() {
  local i="${1:?instance number}"
  shift
  docker logs "$@" "$PREFIX-$i"
}

cmd_build_tools() {
  docker build -t "$TOOLS_IMAGE" "$HERE/tools"
}

cmd_tools() {
  docker image inspect "$TOOLS_IMAGE" >/dev/null 2>&1 || cmd_build_tools
  local net="--network $NET_NAME"
  [[ "$NET_MODE" == host ]] && net="--network host"
  # shellcheck disable=SC2086
  docker run --rm -i $net --user "$(id -u):$(id -g)" -e HOME=/tmp \
    -v "$HERE:/interop" -w /interop "$TOOLS_IMAGE" "$@"
}

case "${1:-}" in
  up) shift; cmd_up "$@" ;;
  down) shift; cmd_down "$@" ;;
  status) cmd_status ;;
  logs) shift; cmd_logs "$@" ;;
  tools) shift; cmd_tools "$@" ;;
  build-tools) cmd_build_tools ;;
  *) sed -n '2,22p' "$0"; exit 1 ;;
esac
